language: java
dist: trusty

jdk:
  - oraclejdk8

before_script:
  - cd Module2/springhometask

script:
  - mvn clean compile test
  
notifications:
  email:
    recipients: #will receive notification, if admin turn it on, in https://github.com/settings/
        - maksym_mazurkevych@epam.com
    on_success: never
    on_failure: always